AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Joya no Commit
Globals:
  Function:
    Timeout: 3
Resources:
  Webhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://masarakki-sam-deploy/f3415963a8ceb5bdf69c8fa5cacd703a
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
Outputs:
  Wehbook:
    Value:
      Fn::Sub: https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/
