AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Joya no Commit
Globals:
  Function:
    Timeout: 3
Resources:
  Webhook:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: webhook/
      Handler: app.lambdaHandler
      Runtime: nodejs12.x
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /webhook
            Method: post
Outputs:
  Wehbook:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/webhook/"
